### PR TITLE
A more sensible default for CM Auto Brightness on the Vision?

### PR DESCRIPTION
**Pull request by ahilliard**
Hi, I've tried to improve the default Auto Brightness settings for the Vision/G2.  The current default autobrightness ranges from 11..2601, which doesn't match the light sensor output from 1..1024. This means the auto brightness isn't responsive in dim-to-dark environments, and it skips steps.

This patch matches the overlay config.xml's "config_autoBrightnessLevels" to the existing libsensors/LightSensor.cpp.  Explanation below:

Since the HTC Vision's light sensor can only output 10 values (see LightSensor.cpp):

1 3 5 19 26 69 219 309 498 1024

...the config_autoBrightnessLevels array should have 10 'stops', equally spaced (on a log scale) between the possible lightsensor values, to make brightness transitions as smooth as possible while minimizing 'hunting'.

0 2 4 10 22 42 123 260 392 714

As for the values in the config_autoBrightnessLcdBacklightValues array, I started from a pitch-black-room screen brightness of 40, to a full-daylight brightness of 255, then interpolated with an exponential function (to match how the human eye sees brightness).  Feel free to brighten these values up if you think they will cause too many dim complaints.

I hope this might make its way to Andromadus, I'm loving their CM9 alpha.  Thanks!

### CODE REVIEW

**Comment by ahilliard** [comment]
Sorry for noob mistake, copy-pasting stripped the comment indentations.  Fixed.

**Comment by Kali-** [comment]
1) changes need to be reviewed on our review system http://wiki.cyanogenmod.com/wiki/Howto:_Gerrit
2) the 0-1024 assumption is wrong, this value will be referred to the sensor hal, which should be 0-10240 lux and not 0-1024 (froyo)
- just looked on vision libsensors and it still use froyo scale 0-1024, so something on vision LS is definitely wrong

**Comment by ahilliard** [comment]
Ah, no wonder nobody was contributing. Thanks for the guidance, I'll try and learn how to set up git and use Gerrit.

Sounds like the vision light sensor code should be fixed rather than just patching it with config overlays.  In your experience, what's the best way to encourage that?  Should I do my best to hack together a change to LightSensor.cpp (maybe just changing the constants to a 0-10240 range, without really knowing the actual lux values), submit it on Gerrit, and hope some more competent/conscientious coder sees what I'm trying to do and fixes it properly?

**Comment by ahilliard** [comment]
On looking further, I won't try messing with libsensors, since it seems cyanogen is behind the 0-1024 range on the Vision hardware:

https://github.com/CyanogenMod/android_device_htc_vision/commit/2b53447ec6b2a3fd3e299428d359b3603db19025

Why did he change it back to the froyo standard, I wonder?  Ah well, am trying to get repo working and will submit the config.xml changes for review.

**Pull request closed without merging**
